version: "3"

networks:
  frontend:
    driver: bridge

services:
  proxy:
    build: ./proxy
    environment:
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=3000
    image: app/proxy:0.0.1
    ports:
      - "80:80"
    networks:
      - frontend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        env: production
        working_dir: /usr/app
    # command: npm run start
    container_name: elm
    env_file:
      - ./list.env
    environment:
      - BUNDLE_DIR=dist
      - FRONTEND_ROOT_PATH=/usr/app/dist
      - FRONTEND_PORT=3000
      - NODE_ENV=production
    image: app/frontend:0.0.1
    networks:
      - frontend
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_default_ttl=65
