version: "2.4"

services:
  frontend:
    build:
      context: ./frontend
      args:
        env: development
        working_dir: /usr/app
    command: npm run dev
    container_name: elm
    env_file:
      - ./list.env
    environment:
      - NODE_ENV=development
      - DEV_SERVER_PORT=3000
    image: app/frontend:dev
    ports:
      - 3000:3000
    # restart: unless-stopped
    # stdin_open: true
    # tty: true
    volumes:
      - ./frontend/src:/usr/app/src
