version: "3"

networks:
  frontend:
    driver: bridge

services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:8080"
    networks:
      - frontend
    # volumes:
    #   - ./proxy/conf:/etc/nginx

  frontend:
    build:
      context: ./frontend
      args:
        env: production
    container_name: elm
    networks:
      - frontend
