version: "3.4"

networks:
  frontend:
    driver: bridge

services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:8080"
    networks:
      - frontend
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: ./frontend
      target: prod
      args:
        env: production
    container_name: elm
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
